name: CI

on:
  pull_request:
jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET CORE
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore OnixDataStandard.sln
    - name: Build
      run: dotnet build OnixDataStandard.sln --no-restore
    - name: Test
      run: dotnet test OnixDataStandard.sln --no-build --verbosity normal --logger trx /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
        /p:Exclude=\"[OnixData.Standard.BaseTests]*\" /p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute\"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    
      with:
        name: .NET Tests results           
        path: '**/TestResults/*.trx'    
        reporter: dotnet-trx
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: '**/TestResults/coverage.info'
        minimum-coverage: 0
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
