name: 'Test Report and Code Coverage'

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  
jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - name: .NET Tests Results
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: .NET Tests results           
        path: '**/**/*.trx'    
        reporter: dotnet-trx  
    - name: Code Coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        artifact-name: code-coverage-report
        minimum-coverage: 0
        coverage-files: | 
          'OnixData.Standard.Net5Tests/TestResults/coverage.info'
          'OnixData.Standard.CoreTests/TestResults/coverage.info'
          'TestResults/coverage.info'
          'TestResults/coverage.info'
          'coverage.info'
          '*.info'
        github-token: ${{ secrets.GITHUB_TOKEN }}
