name: Test Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - name: .NET Tests Results
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: .NET Tests results           
        path: '*.trx'    
        reporter: dotnet-trx  
    - name: Code Coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: 'coverage.info'
        minimum-coverage: 0
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
