name: 'Test Report'

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  
jobs:
  report:
    name: Reports processing
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: .NET Tests Results
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: .NET Tests results           
        path: '**/**/*.trx'    
        reporter: dotnet-trx
