name: 'Test Report and Code Coverage'

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  
jobs:
  report:
    name: Reports
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Download code coverage from GitHub
      uses: actions/download-artifact@v2.0.10
      with:
        name: code-coverage-report
        path: coverage
    - name: .NET Tests Results
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: .NET Tests results           
        path: '**/**/*.trx'    
        reporter: dotnet-trx  
    - name: Code Coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        artifact-name: code-coverage-processed-report
        name: Code Coverage
        coverage-files: '**/TestResults/coverage.info'
        minimum-coverage: 0
        github-token: ${{ secrets.GITHUB_TOKEN }}
